### ISSUE TITLE
Documentation uses HTML frames

### ISSUE THREAD

**Issue by towerofnix** [Mrcomputer1/MrcScript#2]
[Please no.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frameset#wikiArticle)

**Comment by Mrcomputer1** [comment]
I only used frameset and frames because I had no internet connection so I could not find a better way to do it (and I did not think of iframe :stuck_out_tongue: )

**Comment by Mrcomputer1** [comment]
The docs now use iframes :smile:
